baseurl = "https://carsdotcom.github.io/windshieldjs/"
languageCode = "en-us"
title = "WindshieldJS"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Cars.com"
	description = "WindshieldJS - An Enterprise Rendering Plugin for Hapi.js"
	copyright = "Released under the Apache 2.0 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/carsdotcom/windshieldjs"

	version = "1.2.3"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-purple"
    	accent  = "green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "carsdotcom"
	email   = "mheller-ogden@cars.com"


[[menu.main]]
	name   = "WindshieldJS"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants = true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
